### PR TITLE
Handle wildcard headers

### LINKED ISSUE #66: Some accept headers have unexpected behavior
Some accept headers behave unexpectedly. 
For example the **\*/\*** media type does not allow the ServerSentEventMiddleware to trigger. 

If the accept header text/event-stream is configured as **not** required then sending any accept header except text/event-stream will cause ServerSentEventMiddleware to not trigger properly. Which indirectly makes omitting accept headers required (unless the acceot header includes **text/event-stream**).

I propose two changes:

1. allow **\*/\*** to pass the accept headers check regardless of configuration. (This is also the standard accept header in postman so it might make barrier of entry lower)
2. make the check for accept headers exit early if the environment is configured to not require **text/event-stream** present in the accept headers. Skipping all other checks and returning true.

### PR DESCRIPTION
**Pull request by krebil**
Fixes #66

### CODE REVIEW

File: Lib.AspNetCore.ServerSentEvents/ServerSentEventsMiddleware.cs [hunk 1]
```diff
@@ -114,6 +114,8 @@ public async Task Invoke(HttpContext context, IPolicyEvaluator policyEvaluator)
             }
         }
 
+        private static readonly string[] AcceptedHeaders = new[] { "*/*", "text/*", Constants.SSE_CONTENT_TYPE };
```
Comment (tpeczek) [inline Lib.AspNetCore.ServerSentEvents/ServerSentEventsMiddleware.cs]: I know that this is a small array, but the `.Contains` call later will be done quite often so pushing this from O(N) complexity to O(1) complexity by switching to HashSet<T> should still have value. Can you please make an adjustment?

Comment (tpeczek) [inline Lib.AspNetCore.ServerSentEvents/ServerSentEventsMiddleware.cs]: Also please move this to the top with other fields.

File: Test.AspNetCore.ServerSentEvents/Unit/Middleware/HandshakeTests.cs [hunk 2]
```diff
@@ -95,6 +95,21 @@ public async Task Invoke_SseRequestWithMultipleAcceptHeadersWithNotEventStreamAc
             Assert.Null(context.Response.ContentType);
         }
         
+        
+        [Theory]
+        [InlineData("*/*")]
+        [InlineData("text/*")]
+        [InlineData(SSE_CONTENT_TYPE)]
+        public async Task Invoke_SseRequestWithAcceptedHeader_Accepts(string header)
```
Comment (tpeczek) [inline Test.AspNetCore.ServerSentEvents/Unit/Middleware/HandshakeTests.cs]: I like the `InlineData` approach. I don't think that we need two `Invoke_SseRequestWithEventStreamAcceptHeader_Accepts`, if I'm not wrong this one completely replaces the one higher up, so in fact you can modify that one and there is no need to add this one.

**Review by tpeczek — CHANGES_REQUESTED** [review]

File: Lib.AspNetCore.ServerSentEvents/ServerSentEventsMiddleware.cs (hunk 1 above)
Comment (krebil) [reply Lib.AspNetCore.ServerSentEvents/ServerSentEventsMiddleware.cs]: I would argue that iterating a small array is faster than using hashset. But I don't mind changing it if you prefer the more scalable option.

Comment (krebil) [reply Lib.AspNetCore.ServerSentEvents/ServerSentEventsMiddleware.cs]: No problem

File: Test.AspNetCore.ServerSentEvents/Unit/Middleware/HandshakeTests.cs (hunk 2 above)
Comment (krebil) [reply Test.AspNetCore.ServerSentEvents/Unit/Middleware/HandshakeTests.cs]: This is true. Some repos I've worked on disliked the idea of deleting tests.

I'm happy to consolidate the two tests into one

File: Lib.AspNetCore.ServerSentEvents/ServerSentEventsMiddleware.cs (hunk 1 above)
Comment (tpeczek) [reply Lib.AspNetCore.ServerSentEvents/ServerSentEventsMiddleware.cs]: Please do :)

Comment (tpeczek) [reply Lib.AspNetCore.ServerSentEvents/ServerSentEventsMiddleware.cs]: We can also be really professional about it and benchmark it. Currently there are only benchmarks for `ServerSentEventsService` so that would mean setting up a benchmarks for `ServerSentEventsMiddleware` from scratch.

Comment (krebil) [reply Lib.AspNetCore.ServerSentEvents/ServerSentEventsMiddleware.cs]: I did a benchmark on `hashset.contains` and `array.contains` with a bounded dataset of 3 entries. And hashset seems superior. Especially when the hashset/array does not contain the string that is being looked up. I wasn't sure how to test this in a good way in your application, I'm not super well-versed in `benchmarkdotnet`. 

Regardless I have substituted the array for a hashset .

**Comment by krebil** [comment]
Not sure why the tests are failing in the CI. Perhaps I broke something by renaming the test?

**Review by tpeczek — APPROVED** [review]

File: Lib.AspNetCore.ServerSentEvents/ServerSentEventsMiddleware.cs (hunk 1 above)
Comment (tpeczek) [reply Lib.AspNetCore.ServerSentEvents/ServerSentEventsMiddleware.cs]: Thank you :)

**Comment by tpeczek** [comment]
> Not sure why the tests are failing in the CI. Perhaps I broke something by renaming the test?

No, it seems there is a flaky test, I'll create an issue to dig into that in future.
